
CREATE TABLE public.produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  is_new BOOLEAN NOT NULL DEFAULT false,
  hue INTEGER NOT NULL DEFAULT 330,
  image TEXT,
  images JSONB NOT NULL DEFAULT '[]'::jsonb,
  active BOOLEAN NOT NULL DEFAULT true,
  sort_order INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.produtos TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.produtos TO authenticated;
GRANT ALL ON public.produtos TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.produtos_id_seq TO anon, authenticated, service_role;

ALTER TABLE public.produtos ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Qualquer um pode ver produtos"
  ON public.produtos FOR SELECT
  USING (true);

CREATE POLICY "Qualquer um pode criar produtos"
  ON public.produtos FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Qualquer um pode atualizar produtos"
  ON public.produtos FOR UPDATE
  USING (true) WITH CHECK (true);

CREATE POLICY "Qualquer um pode excluir produtos"
  ON public.produtos FOR DELETE
  USING (true);

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER update_produtos_updated_at
  BEFORE UPDATE ON public.produtos
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE INDEX produtos_sort_order_idx ON public.produtos (sort_order, id);
